[package]
name = "pdf-test"
version = "0.1.0"
authors = ["askepen <aske@vhg26.dk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
printpdf = "^0.3.2"
xml-rs = "^0.8.3"
zip-extract = "^0.1.0"
