[package]
name = "pdf-test"
version = "0.1.0"
authors = ["askepen <aske@vhg26.dk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
printpdf = "0.3.2"
serde_derive = "1.0"
serde = { version="^1.0.117", features = ["derive"] }
serde-xml-rs = "0.4.0"
zip-extract = "0.1.0"
regex = "1"